config/routes.rb
TestPrj::Application.routes.draw do
  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout
     
  match 'forgot' => 'users#forgot', :as => :forgot 
  
  match  'reset/:reset_code' => 'users#reset', :as => :reset

 

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  root :to => "users#index"

end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken
  

  set_table_name 'users'

  validates :login, :presence   => true,
                    :uniqueness => true,
                    :length     => { :within => 3..40 },
                    :format     => { :with => Authentication.login_regex, :message => Authentication.bad_login_message }

  validates :name,  :format     => { :with => Authentication.name_regex, :message => Authentication.bad_name_message },
                    :length     => { :maximum => 100 },
                    :allow_nil  => true

  validates :email, :presence   => true,
                    :uniqueness => true,
                    :format     => { :with => Authentication.email_regex, :message => Authentication.bad_email_message },
                    :length     => { :within => 6..100 }

  before_create :make_activation_code 

  # HACK HACK HACK -- how to do attr_accessible from here?
  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  attr_accessible :login, :email, :name, :password, :password_confirmation


  # Activates the user in the database.
  def activate!
    @activated = true
    self.activated_at = Time.now.utc
    self.activation_code = nil
    save(:validate => false)
  end

  # Returns true if the user has just been activated.
  def recently_activated?
    @activated
  end

  def active?
    # the existence of an activation code means they have not activated yet
    activation_code.nil?
  end

  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.  
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(login, password)
    return nil if login.blank? || password.blank?
    u = where(['login = ? and activated_at IS NOT NULL', login]).first # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end

  def email=(value)
    write_attribute :email, (value ? value.downcase : nil)
  end
  
  
  
  def create_reset_code  
  @reset = true 
  
  #self.attributes = {:reset_code => Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )}  
  self.reset_code = Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )
  save(false)  
  end  



  
  def recently_reset?  
    @reset  
  end  
  
  def delete_reset_code  
    self.attributes = {:reset_code => nil}  
    save(false)  
  end  
  
  

  protected
    
  def make_activation_code
  
      self.activation_code = self.class.make_token
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Be sure to include AuthenticationSystem in Application Controller instead
  include AuthenticatedSystem
  

  # render new.rhtml
  def new
    debugger
    @user = User.new
  end
 
  def create
    
    logout_keeping_session!
    @user = User.new(params[:user])
    success = @user && @user.save
    if success && @user.errors.empty?
      redirect_back_or_default('/', :notice => "Thanks for signing up!  We're sending you an email with your activation code.")
    else
      flash.now[:error]  = "We couldn't set up that account, sorry.  Please try again, or contact an admin (link is above)."
      render :action => 'new'
    end
  end

  def activate
    logout_keeping_session!
    user = User.find_by_activation_code(params[:activation_code]) unless params[:activation_code].blank?
    case
    when (!params[:activation_code].blank?) && user && !user.active?
      user.activate!
      redirect_to '/login', :notice => "Signup complete! Please sign in to continue."
    when params[:activation_code].blank?
      redirect_back_or_default('/', :flash => { :error => "The activation code was missing.  Please follow the URL from your email." })
    else 
      redirect_back_or_default('/', :flash => { :error  => "We couldn't find a user with that activation code -- check your email? Or maybe you've already activated -- try signing in." })
    end
  end


  
 def forgot  
  if request.post?  
    user = User.find_by_email(params[:user][:email])  
  logger.info("你想輸出的字串")

  
    respond_to do |format|  
      if user  
        user.create_reset_code  
        flash[:notice] = "---Reset code sent to #{user.email}"  

        format.html { redirect_to login_path }  
  #     format.xml { render :xml => '<img src="http://net.tutsplus.com/wp-includes/images/smilies/icon_mad.gif" alt=":x" class="wp-smiley">' , :ml => user.email, :status => :unprocessable_entity }  
      else  
        flash[:error] = "#{params[:user][:email]} does not exist in system"  
  
  
  
        format.html { redirect_to login_path }  
  #      format.xml { render :xml => '<img src="http://net.tutsplus.com/wp-includes/images/smilies/icon_mad.gif" alt=":x" class="wp-smiley">' , :ml => user.email, :status => :unprocessable_entity }  
      end  
    end  
 end
 end
  
  
def reset  
  @user = User.find_by_reset_code(params[:reset_code]) unless params[:reset_code].nil?  
  if request.post?  
    if @user.update_attributes(:password => params[:user][:password], :password_confirmation => params[:user][:password_confirmation])  
      self.current_user = @user  
      @user.delete_reset_code  
      flash[:notice] = "Password reset successfully for #{@user.email}"  
      redirect_to login_path  
    else  
      render :action => :reset  
    end  
  end  
end    


def index
  #I18n.locale = :en

  #@temp_user = User.find(2) 
end

end

app/helpers/users_helper.rb
module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), user_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag = options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

app/views/users/_user_bar.html.erb
<% if logged_in? -%>
  <div id="user-bar-greeting">Logged in as <%= link_to_current_user :content_method => :login %></div>
  <div id="user-bar-action"  >(<%= link_to "Log out", logout_path, { :title => "Log out" }    %>)</div>
<% else -%>
  <div id="user-bar-greeting"><%= link_to_login_with_IP 'Not logged in', :style => 'border: none;' %></div>
  <div id="user-bar-action"  ><%= link_to "Log in",  login_path,  { :title => "Log in" } %> /
                               <%= link_to "Sign up", signup_path, { :title => "Create an account" } %></div>
<% end -%>

app/views/users/forgot.html.erb
<h1>forgot password</h1>
<%= error_messages_for :user %>  
  
<% form_for :user do |f| -%>  
  <p>  
    Reset Password Request  
  </p>  
  
  <p>  
    <label for="email">Email</label><br />  
    <%= f.text_field :email %>  
  </p>  
  
  <p>  
    <%= link_to "Cancel", login_path %>  
    <%= submit_tag 'Submit' %>  
  </p>  
<% end -%>  

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Private Spaces</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>


<h1> <%=t :title %></h1>


<h1> <%=t :MyPrivateSpace %></h1>

<h1> My Private Spaces </h1>


<div class="user">  
  <%= link_to (t :signup), :signup unless logged_in? %>  
</div>  

<div class="user">  
  <%= link_to (t :login, :locale => :en), :login unless logged_in? %>  
</div>  

<p><%= l Time.now, :format => :short %></p>

<!--
<%= debug @temp_user %>
<%= debug "XXXXXXXXXXXX" %>
-->

<body style="background: #EEEEEE;">


<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign up as a new user</h1>
<% @user.password = @user.password_confirmation = nil %>

<%= error_messages_for :user %>


<% # users_path是app的一個attribute, 它的值跟route.rb有關  %>
<% # 此時users_path是 /users, 所以這個form在commit後就會執行models/user.rb  %>
<% #   %>
<%= form_for :user, :url => users_path do |f| -%>


<p><%= label_tag 'login' %><br/>
<%= f.text_field :login %></p>

<p><%= label_tag 'email' %><br/>
<%= f.text_field :email %></p>

<p><%= label_tag 'password' %><br/>
<%= f.password_field :password %></p>

<p><%= label_tag 'password_confirmation', 'Confirm Password' %><br/>
<%= f.password_field :password_confirmation %></p>

<p><%= submit_tag (t :signup) %></p>
<% end -%>

app/views/users/reset.html.erb
# app/views/users/reset.html.erb  
  
<%= error_messages_for :user %>  
  
<% form_for :user do |f| -%>  
  <p>  
    Pick a new password for <span><%= @user.email %></span>  
  </p>  
  
  <p>  
    <label for="password">Password</label><br />  
    <%= f.password_field :password %>  
  </p>  
  
  <p>  
    <label for="password">Confirm Password</label><br />  
    <%= f.password_field :password_confirmation %>  
  </p>  
  
  <p>  
    <%= submit_tag 'Reset' %>  
  </p>  
<% end -%>  